sudo: false
language: python

python:
  - '2.6'
  - '2.7'
  - '3.4'
  - '3.5'
  - pypy

env:
  - DJANGO_VERSION=1.8.x
  - DJANGO_VERSION=1.7.x
  - DJANGO_VERSION=1.6.x

matrix:
  exclude:
  - python: '2.6'
    env: DJANGO_VERSION=1.7.x
  - python: '2.6'
    env: DJANGO_VERSION=1.8.x
  - python: '3.5'
    env: DJANGO_VERSION=1.6.x
  - python: '3.5'
    env: DJANGO_VERSION=1.7.x

install:
  - pip install tox

script:
  - tox -e "$TRAVIS_PYTHON_VERSION-$DJANGO_VERSION"

after_success:
  - pip install "coveralls==1.0" coverage
  - coverage report
  - coveralls

notifications:
  hipchat:
    on_success: always
    rooms:
      secure: clwj0J243Ta+guLsnI9L1ghnWOrQGRttfFFg3PCAGlPwEAdD8QQih+DRWDPDNsgwC5jfiZRz5+t6xjD0lzbUdtyXrvbuc6aUGnmxrHvq9wslXt+TEajPnVrxobQLy7HxtfOlXI0XlTFz+mk19i3BLja9OtEFPjStOuWeX5MeUgM=
    template:
      - "<strong>%{repository_name}</strong> <a href='%{build_url}'>build %{build_number}</a> (%{branch}) %{message}. (%{duration})"
    format: html
